import requests
from bs4 import BeautifulSoup


def getRecipe(name_recipe):
    # URL GENERATED BY RECIPE NAME FOR GET REQUEST TO allrecipes.com
    name_recipe_parsed = name_recipe.split(" ")   
    url = "https://www.allrecipes.com/search/results/?wt="
    i = 0
    len_ = len(name_recipe_parsed)
    for s in name_recipe_parsed:
        if i != len_ - 1:
            url+=s+"%20"
        else:
            url += s
        i += 1
    url += "&sort=re"
    r = requests.get(url)
    
    # BUILD STRING FOR COMPARE
    string_comp = ""
    i = 0
    for s in name_recipe_parsed:
        if i != len_-1:
            string_comp += s.lower().replace("'","")+"-"
        else:
            string_comp += s.lower()
        i += 1

    # PARSER FOR FIND RECIPE PAGE
    soup = BeautifulSoup(r.text, 'html.parser')
    cards = soup.find_all(class_="fixed-recipe-card__h3")  
    for c in cards:
        url_recipe = c.find("a").get('href')
        if str(url_recipe).find(string_comp) != -1:
            break    
    r2 = requests.get(url_recipe)

    # PARSER FOR EXTRACT STEPS OF RECIPES
    soup = BeautifulSoup(r2.text, "html.parser")
    steps = soup.find_all(class_="recipe-directions__list--item")
    calories = soup.find(itemprop="calories")
    prep_time = soup.find(class_="prepTime")
      
    i = 0
    for i in range(0,len(steps)):
        steps[i] = steps[i].text.replace("\n","").replace("  ", "")
    
    return steps, prep_time, calories

